# Generated by Django 5.2.7 on 2025-10-11 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_assignment_options_job_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=128, null=True)),
                ('event', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('client_ts', models.DateTimeField(blank=True, null=True)),
                ('server_ts', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
