# Generated by Django 5.2.7 on 2025-11-01 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_synclog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_action', models.CharField(choices=[('reassign', 'Reassign'), ('notify', 'Notify customer'), ('escalate', 'Escalate')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='low', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('ignored', 'Ignored')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_actions', to='core.job')),
                ('suggested_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.technician')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
